import regeneratorRuntime from "regenerator-runtime";

import "../scss/styles.scss";

import "../images/cart_icon.png";
import "../images/logo.png";
import "../images/main_background01.jpg";
import "../images/right_arrow.png";
import "../images/mail_icon.png";
import "../images/phone_icon.png";
import "../images/scroll_icon.png";
import "../images/scroll_back01.jpg";
import "../images/scroll_back02.jpg";
import "../images/scroll_back03.jpg";
import "../images/slice_back01.jpg";
import "../images/slice_back03.jpg";
import "../images/brand_back01.jpg";
import "../images/brand01.png";
import "../images/brand02.png";
import "../images/brand03.png";
import "../images/brand04.jpg";
import "../images/brand05.png";
import "../images/brand06.png";
import "../images/brand07.png";
import "../images/brand08.png";
import "../images/brand09.png";
import "../images/brand10.jpg";
import "../images/brand11.png";
import "../images/brand12.jpg";
import "../images/brand13.png";
import "../images/pageup_icon.png";